[project]
name = "leashedlibrus-build-system"
version = "0.1.0"
description = "Build system for LeashedLibrus.user.js"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "arguably>=1.3.0",
    "tcrutils>=13.1.39",
]

[tool.mypy]
disable_error_code = "import-untyped"
